/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  stock?: number;
  variant?: "newarrival" | "bestseller" | "featured";
  categories?: Array<string>;
  status?: "sale" | "new" | "hot";
};

// ✅ Manually added — TypeGen returns Array<never> due to missing category schema in schema.json
export type Category = {
  _id: string;
  title: string;
  slug: {
    current: string;
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
    };
    _type: "image";
  };
  productCount?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Product
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ./sanity/lib/queries.ts
// Variable: getCategoriesQuery
// Query: *[_type == "category"]{ _id, title, slug, image, "productCount": count(*[_type=="product" && references(^._id)])}
export type GetCategoriesQueryResult = Array<Category>;

// Variable: getAllBrands
// Query: *[_type == "brand"] | order(title asc){ _id, title, slug, logo}
export type GetAllBrandsResult = Array<never>;

// Source: ./sanity/quaries/query.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand"] | order(title asc){ _id, title, slug, logo }
export type BRANDS_QUERYResult = Array<never>;

// Query TypeMap
import "@sanity/client";
import { Image } from "sanity";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == \"category\"]{\n  _id,\n  title,\n  slug,\n  image,\n  \"productCount\": count(*[_type==\"product\" && references(^._id)])\n}\n": GetCategoriesQueryResult;
    "\n*[_type == \"brand\"] | order(title asc){\n  _id,\n  title,\n  slug,\n  logo\n}\n": GetAllBrandsResult;
    "\n  *[_type == \"brand\"] | order(title asc){\n    _id,\n    title,\n    slug,\n    logo\n  }\n": BRANDS_QUERYResult;
  }
}

export type Blog = {
  _id: string;
  title?: string;
  slug?: {
    current?: string;
  };
  mainImage?: Image;
  publishedAt?: string;
};
// ✅ Add this manually — for getProductsByCategory query result
export type ProductQueryResult = {
  _id: string;
  name: string;
  price: number;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
    };
    _type: "image";
    _key: string;
  }>;
};
